tank:
  enabled: true
  package: yandextank.plugins.DataUploader
  token_file: .token

phantom:
  address: localhost:7080
  ammofile: ammo.txt
  ammo_type: uripost
  load_profile:
    load_type: rps
    schedule: const(5000, 200s)
  instances: 1000
console:
  enabled: true
telegraf:
  enabled: false
